ngpu: 1

dataset:
  num_classes: 8
  training:
    csi_info_path: datasets/annotations/val_video_info.csv
    csi_anno_path: datasets/annotations/val_Annotation_ours.csv
    csi_data_path: ./datasets/smartwifi/validation_npy/
    clip_length: 2000
    clip_stride: 500
    
  testing:
    csi_info_path: datasets/annotations/test_video_info.csv
    csi_anno_path: datasets/annotations/test_Annotation_ours.csv
    csi_data_path: ./datasets/smartwifi/test_npy/
    clip_length: 2000
    clip_stride: 500

model:
  name: SL
  in_channels: 60

training:
  batch_size: 4
  learning_rate: 1e-5
  weight_decay: 1e-3
  max_epoch: 10
  focal_loss: true
  checkpoint_path: ./models/SL/
  random_seed: 2020

testing:
  conf_thresh: 0.01
  top_k: 250
  nms_thresh: 0.9
  nms_sigma: 0.95
  checkpoint_path: ./models/SL/
  output_path: ./output/SL/

evaling:
  gt_json: ./datasets/annotations/gt.json