ngpu: 2

dataset:
  num_classes: 8
  training:
    csi_info_path: datasets/annotations/val_video_info.csv
    csi_anno_path: datasets/annotations/val_Annotation_ours.csv
    csi_data_path: ./datasets/smartwifi/validation_npy/
    clip_length: 4096
    clip_stride: 2000
    
  testing:
    csi_info_path: datasets/annotations/test_video_info.csv
    csi_anno_path: datasets/annotations/test_Annotation_ours.csv
    csi_data_path: ./datasets/smartwifi/test_npy/
    clip_length: 4096
    clip_stride: 2000
    
model:
  name: TALFi
  in_channels: 60

training:
  batch_size: 2
  learning_rate: 4e-5
  weight_decay: 1e-3
  max_epoch: 37
  focal_loss: true
  # checkpoint_path: ./models/TALFi/
  checkpoint_path: /datadisk/liuzhendong
  random_seed: 2020

testing:
  conf_thresh: 0.01
  top_k: 250
  nms_thresh: 0.5
  nms_sigma: 0.95
  # checkpoint_path: ./models/TALFi/
  
  checkpoint_path: /datadisk/liuzhendong/
  output_path: ./output/TALFi/

evaling:
  gt_json: ./datasets/annotations/gt.json